---
apiVersion: v1
kind: Service
metadata:
  name: k8s-cert-exp
  labels:
    app: k8s-cert-exp
    service: k8s-cert-exp
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: k8s-cert-exp
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ilker-k8s-cert-exp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-cert-exp-v1
  labels:
    app: k8s-cert-exp
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-cert-exp
      version: v1
  template:
    metadata:
      labels:
        app: k8s-cert-exp
        version: v1
    spec:
      serviceAccountName: ilker-k8s-cert-exp
      containers:
      - name: k8s-cert-exp
        image: ilkerispir/k8s-cert-exp
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
