- name: Render k8s-cert-exp services yml file
  template:
    dest: /tmp/k8s-cert-exp.yml
    src: k8s-cert-exp.yml.j2

- name: Deploy k8s-cert-exp service
  command: "kubectl apply -f /tmp/k8s-cert-exp.yml"

- name: Render k8s-cert-exp ingress yml file
  template:
    dest: /tmp/ingress.yml
    src: ingress.yml.j2

- name: Deploy k8s-cert-exp ingress
  command: "kubectl apply -f /tmp/ingress.yml"