---
prometheus_stack:
  chart_version: "21.0.0"

  deployment:
    namespace: monitoring

  domain_name:
    suffix: ilkerispir.com

  prometheus:
    resources:
      requests:
        cpu: 1000m
        memory: 4000Mi
      limits:
        cpu: 2000m
        memory: 4000Mi
