---
- name: Add Jenkins chart repo
  community.kubernetes.helm_repository:
    name: jenkins
    repo_url: https://charts.jenkins.io

- name: Render values file
  template:
    dest: /tmp/jenkins-values.yml
    src: jenkins-values.yml.j2

- name: Install Jenkins
  community.kubernetes.helm:
    name: jenkins
    chart_ref: jenkins/jenkins
    chart_version: "{{ jenkins.chart_version }}"
    values_files:
      - /tmp/jenkins-values.yml
    release_namespace: jenkins
    create_namespace: true
    update_repo_cache: true
