---
- name: Deploy Tekton
  command: "kubectl apply -f https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml"

- name: Deploy Tekton Dasboard
  command: "kubectl apply -f https://storage.googleapis.com/tekton-releases/dashboard/latest/tekton-dashboard-release.yaml"

- name: Render k8s-cert-exp ingress yml file
  template:
    dest: /tmp/tekton-ingress.yml
    src: tekton-ingress.yml.j2

- name: Deploy Tekton ingress
  command: "kubectl apply -f /tmp/tekton-ingress.yml"
